name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (gcc, readline)
        run: |
          sudo apt update
          sudo apt install -y gcc build-essential libreadline-dev unzip curl

      - name: Download and extract build-wrapper
        run: |
          curl -sSLo bw.zip https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip bw.zip

      - name: Compile source files with build-wrapper
        run: |
          ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw-output \
          gcc -Wall -Wextra -Werror -I./includes -c *.c

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=RafPetrosyan_qa_test_minishell
            -Dsonar.organization=rafpetrosyan
            -Dsonar.cfamily.build-wrapper-output=bw-output
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
