name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17 (required by SonarCloud)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential make gcc libncurses-dev libreadline-dev wget unzip

      - name: Download build-wrapper
        run: |
          wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip build-wrapper-linux-x86.zip

      - name: Build custom readline (static)
        working-directory: libraries/readline-8.2
        run: |
          ./configure --prefix=$GITHUB_WORKSPACE/libraries/readline
          make
          make install

      - name: Clean project
        run: make fclean || true

      - name: Build with build-wrapper
        run: |
          ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 \
            --out-dir bw-output --project-root . -- make all

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=RafPetrosyan_qa_test_minishell
            -Dsonar.organization=rafpetrosyan
            -Dsonar.sources=sources,includes
            -Dsonar.cfamily.compile-commands=bw-output/compile_commands.json
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
