name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (compiler, unzip, wget)
        run: |
          sudo apt update
          sudo apt install -y build-essential wget curl unzip

      - name: Download and install GNU Readline 8.2 locally
        run: |
          mkdir -p libraries
          wget https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz
          tar -xzf readline-8.2.tar.gz
          mv readline-8.2 libraries/
          cd libraries/readline-8.2
          ./configure --prefix=$GITHUB_WORKSPACE/libraries/readline-8.2/install
          make
          make install
          cd ../..

      - name: Download and prepare build-wrapper
        run: |
          curl -sSLo bw.zip https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip bw.zip
          chmod +x build-wrapper-linux-x86/build-wrapper-linux-x86-64

      - name: Compile project with build-wrapper (no Makefile)
        run: |
          ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 \
            --out-dir bw-output \
            bash -c 'for file in *.c; do gcc -Wall -Wextra -Werror \
            -I./includes \
            -I./libraries/readline-8.2/install/include \
            -L./libraries/readline-8.2/install/lib \
            -c "$file"; done'

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=RafPetrosyan_qa_test_minishell
            -Dsonar.organization=rafpetrosyan
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=.
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.cfamily.compile-commands=bw-output/compile_commands.json
