# .github/workflows/sonarcloud.yml

name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Download and extract build-wrapper
        run: |
          mkdir -p build-wrapper-linux
          curl -sSLo bw.zip https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip bw.zip -d build-wrapper-linux

      - name: Run build-wrapper around make
        run: |
          ./build-wrapper-linux/build-wrapper-linux-x86-64 --out-dir bw-output make fclean && ./build-wrapper-linux/build-wrapper-linux-x86-64 --out-dir bw-output make

      - name: Run SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
