name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libncurses-dev wget unzip

      - name: Download and install GNU Readline
        run: |
          wget https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz
          tar -xzf readline-8.2.tar.gz
          cd readline-8.2
          ./configure --prefix=$GITHUB_WORKSPACE/libraries/readline-8.2/install
          make
          make install
          cd ..

      - name: Download and prepare build-wrapper
        run: |
          wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip build-wrapper-linux-x86.zip
          chmod +x build-wrapper-linux-x86/build-wrapper-linux-x86-64

      - name: Build with build-wrapper
        run: |
          mkdir -p objects
          SRC_DIR=$(pwd)
          ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw-output env SRC_DIR=$SRC_DIR bash -c '
            for file in *.c; do
              abs_path="$SRC_DIR/$file"
              gcc -Wall -Wextra -Werror \
                  -I./includes \
                  -I./libraries/readline-8.2/install/include \
                  -L./libraries/readline-8.2/install/lib \
                  -c "$abs_path" -o "objects/${file%.c}.o"
            done
          '

      - name: "Debug: show first 20 lines of compile_commands.json"
        run: |
          echo "=== First 20 lines of compile_commands.json ==="
          head -n 20 bw-output/compile_commands.json || echo "Not found"

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=RafPetrosyan_qa_test_minishell
            -Dsonar.organization=rafpetrosyan
            -Dsonar.sources=.
            -Dsonar.cfamily.compile-commands=bw-output/compile_commands.json
            -Dsonar.host.url=https://sonarcloud.io
