name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure readline
        run: |
          cd libraries/readline-8.2
          ./configure --prefix=$GITHUB_WORKSPACE/libraries/readline
          make
          make install
          cd ../..
  
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev

      - name: Download and set up build-wrapper
        run: |
          wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip build-wrapper-linux-x86.zip
          chmod +x build-wrapper-linux-x86/build-wrapper-linux-x86-64

      - name: Clean and build wrapped
        run: |
          make fclean
          rm -rf bw-output
          ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 \
            --out-dir bw-output \
            make


      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
